name: json_dynamic_widget_plugin_svg
description: A plugin to the JSON Dynamic Widget to provide SVG support to the widgets
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_svg

version: 3.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  json_class: ^2.1.2+4
  json_dynamic_widget: ^5.0.0
  json_theme: ^4.0.0
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.6
  websafe_svg: ^2.1.1

false_secrets:
  - example/web/index.html

dev_dependencies:
  flutter_test:
    sdk: flutter
